from .reply import (
    get_phone_keyboard,
    get_cancel_keyboard,
    get_main_reply_keyboard
)
from .inline import (
    get_main_inline_keyboard,
    get_back_to_menu_keyboard,
    get_visa_countries_keyboard,
    get_visa_purposes_keyboard,
    get_timeframes_keyboard,
    get_visa_refusal_keyboard,
    get_refusal_count_keyboard,
    get_convenient_time_keyboard,
    get_study_stages_keyboard,
    get_study_countries_keyboard,
    get_ielts_keyboard,
    get_study_budget_keyboard,
    get_tour_destinations_keyboard,
    get_tours_list_keyboard,
    get_tour_detail_keyboard,
    get_consult_service_keyboard,
    get_admin_lead_keyboard,
    get_assign_manager_keyboard
)

__all__ = [
    "get_phone_keyboard",
    "get_cancel_keyboard",
    "get_main_reply_keyboard",
    "get_main_inline_keyboard",
    "get_back_to_menu_keyboard",
    "get_visa_countries_keyboard",
    "get_visa_purposes_keyboard",
    "get_timeframes_keyboard",
    "get_visa_refusal_keyboard",
    "get_refusal_count_keyboard",
    "get_convenient_time_keyboard",
    "get_study_stages_keyboard",
    "get_study_countries_keyboard",
    "get_ielts_keyboard",
    "get_study_budget_keyboard",
    "get_tour_destinations_keyboard",
    "get_tours_list_keyboard",
    "get_tour_detail_keyboard",
    "get_consult_service_keyboard",
    "get_admin_lead_keyboard",
    "get_assign_manager_keyboard"
]
